### ISSUE TITLE
Fix codecov.io uploads

### ISSUE THREAD

**Issue by noisecapella** [mitodl/rapid-response-xblock#103]
At some point 4 months ago we stopped uploading code coverage to codecov.io. It looks like there's an error due to missing credentials: https://github.com/mitodl/rapid-response-xblock/runs/2410303348#step:4:1867

It's possible we are missing an environment variable with information connecting the repo to codecov. That was handled automatically in Travis when we passed through Travis related environment variables. There might be a similar way to do it via github actions. However it might be easier and cleaner to remove the codecov command from the script and add a github action for the purpose like we do in other repositories: https://github.com/mitodl/micromasters/blob/master/.github/workflows/ci.yml#L96

**Comment by arslanashraf7** [comment]
Closing, Associated PR has been merged.
