### ISSUE TITLE
page scrolls when closing rapid response problem

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#122]
**Steps to Reproduce**

1. Navigate to sequential containing multiple rapid response problems, open problems for response
2. Attempt to close the problems
[Example](https://lms.mitx.mit.edu/learn/course/course-v1:MITx+5.12r_7+2022_Spring/block-v1:MITx+5.12r_7+2022_Spring+type@sequential+block@b1ea2167b6644527969355defd6aaa13/block-v1:MITx+5.12r_7+2022_Spring+type@vertical+block@f38989f4bbc94bd590333438fb79965b)

**Expected Behavior**

The page should remain on the problem that was closed

**Actual Behavior**

When closing the first problem the page does not scroll away, if closing subsequent problems further down on the page it automatically scrolls up to the first problem

As seen in the example below the second problem was closed but the page scrolled up to the response section of the first problem

**Screenshot or Screencast**

![68e98980-9584-11ec-8e4c-9214045daa07](https://user-images.githubusercontent.com/430126/159493562-f954c3a1-4c4f-4b53-aa43-564eb69157de.gif)

### related issue

https://github.mit.edu/mitx/spring-2022/issues/29

**Comment by asadiqbal08** [comment]
@pdpinch Can you please update the screen shot section here ? 
I looked around it but need to look over the screenshot as you attached.
