### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/rapid-response-xblock#136]
The integration tests appear to have broken recently, see: https://github.com/mitodl/rapid-response-xblock/actions/runs/3322756634/jobs/5492225101#step:4:1228

**Comment by arslanashraf7** [comment]
I think It's time we start working on this because some things are being deprecated in edX and we are using a lot of them, e.g. `ItemFactory, Xmodule, Runtime`, etc. I also noticed these changes while working on https://github.com/mitodl/rapid-response-xblock/pull/138.

**Comment by arslanashraf7** [comment]
Done via #139
