### ISSUE TITLE
OLX serialization of asides

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#14]
As a course author, I would like to be able to export my course including all the asides as an XML file. This will allow me to transfer my course between open edX installation, and allow me to edit the source code of my course as an alternative to using Studio. 

### acceptance criteria
- [ ] investigate existing OLX support for asides
- [ ] authoring configuration (e.g. whether rapid responses are "turned on") should be part of the serialization
- [ ] lms configuration (whether the problem is currently "open"; any learner resource data) should *not* be included in the serialization. 

### related issues
- deserialization of asides

**Comment by gsidebo** [comment]
Once #31 merges, I believe all the acceptance criteria will be met. I'll leave this issue open until we do some manual testing post-merge

**Comment by pdpinch** [comment]
#31 merged and we had a demo of serialization on Friday that seemed effective to me. I'm going to close this.
