### ISSUE TITLE
Fix integration tests after the removal of Old Mongo

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/rapid-response-xblock#142]
## Context:

Open edX removed most of the old Mongo and left only enough of its functionality as readable only. The removal was done at https://github.com/openedx/edx-platform/pull/31134.

Our integration tests started to break after the removal of old Mongo, because the tests could access the child components and our tests are mostly breaking because of scope error.

## Solution Guide

[This](https://discuss.openedx.org/t/side-effects-of-old-mongo-removal/11286) is a discussion post that wraps around our problem and some suggestions were provided on this post [here](https://discuss.openedx.org/t/side-effects-of-old-mongo-removal/11286/2) to fix some of the issues in our integration tests.

## Logs
[Here](https://github.com/mitodl/rapid-response-xblock/actions/runs/6247918473/job/16961459460?pr=138) are the logs from the breaking test suit.

## Acceptance Criteria

- [ ] All the tests are running successfully

**Comment by arslanashraf7** [comment]
@Anas12091101 Should we close since we have merged https://github.com/mitodl/rapid-response-xblock/pull/152?

**Comment by anassmohammad** [comment]
@arslanashraf7 yes, I am closing this issue

**Comment by Anas12091101** [comment]
@arslanashraf7 yes, this issue is fixed and we can close it.
