### ISSUE TITLE
Improve test suite execution

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#20]
There are a few issues with local execution of tests for this project:
1. You need to copy the `setup.cfg` from the `edx-platform` repo root into the rapid response repo root for the suite to run correctly
1. You need to manually create a `test_root` directory in the rapid response repo root to avoid `OSError`s being thrown
1. ~~Django migrations are run by default when the test suite is executed, and there is no clean way to disable them. On OSX this takes a very long time to complete. The `paver` test execution commands in `edx-platform` allow the user to indicate that migrations should be skipped. It would be very preferable to enable the same for this test suite~~ Setting the `DISABLE_MIGRATIONS` env variable actually does prevent migrations from running. The huge amount of db-related output is from the tables being created directly from the models. Might not be possible to prevent that and the related performance penalty, but we should at least look into a straightforward way to cut down on the massive amount of logging output

**Comment by noisecapella** [comment]
The first item is no longer an issue, fixed in #22

**Comment by pdpinch** [comment]
What's left to do here?
