### ISSUE TITLE
Open upstream edx-platform PR for XBlockAside fixes

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#24]
`edx-platform` was not equipped to correctly handle `XBlockAside`s for the student and studio views. PRs like https://github.com/mitodl/edx-platform/pull/79 and https://github.com/mitodl/edx-platform/pull/80 were created to fix these issues, and there are probably more fixes to come. When we are confident that we have finished the necessary work in `edx-platform`, we should open an upstream PR. **Note that the work to fix aside integration in LMS caused 191 test failures. We would obviously need to fix those failures, and probably add new tests.**

**Comment by pdpinch** [comment]
When we have an RC for the Residential MITx summer release, we will need to cherry-pick mitodl/edx-platform#79 and mitodl/edx-platform#80 -- does it make sense to make a new PR that combines them and rebases them? This would also be the first step towards an upstream PR.

**Comment by pdpinch** [comment]
I'm moving this back to the backlog for now.

**Comment by pdpinch** [comment]
Also need to upstream https://github.com/mitodl/edx-platform/pull/83

**Comment by pdpinch** [comment]
I think this is a duplicate?

**Comment by amir-qayyum-khan** [comment]
@pdpinch yes it Duplicate.

closing in favour of https://github.com/mitodl/edx-platform/issues/100
