### ISSUE TITLE
Change model column names 

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#25]
ID column names in the `RapidResponseSubmission` and `RapidResponseBlockStatus` are inconsistent. Both models have columns for a problem usage key and a course key, but the names are `problem_id`/`course_id` and `usage_key`/`course_key` respectively. These should be changed to match each other. Suggestion: `problem_usage_key` and `course_key`

**Comment by noisecapella** [comment]
Sounds good with me
