### ISSUE TITLE
display two graphs 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#29]
As an instructor, I'd like to be able to offer the same question multiple times and then be able to compare the results of two runs of the question. This allows me to 

1. Compare student understanding before and after a lesson
2. Use the same question in different course sections

**Comment by roberthouse54** [comment]
- The user will be able to select any previous response set from a dropdown. The dropdown will identify responses by date/time stamp, and number of students who responded. By default, we will show the most recent completed graph. We should also probably have a "None" option, if the professor wants to not display anything.

![image](https://user-images.githubusercontent.com/20047260/37534998-c76ae07c-291c-11e8-9330-c919714e9a74.png)

If the user clicks "Compare Responses", we will display 2 graphs side by side, each with a dropdown, so the user can select any graphs to compare. By default, no graph will be displayed at right. The dropdown label is "Select previous responses to compare." 

![image](https://user-images.githubusercontent.com/20047260/37535416-0a58897e-291e-11e8-98c2-295e04c9167f.png)

![image](https://user-images.githubusercontent.com/20047260/37535481-2e59cc02-291e-11e8-960c-765e531d30a2.png)

The user can close either comparison window to return to the single graph view.
