### ISSUE TITLE
Fix UI for rapid responses problems with no data

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#34]
If a problem is rapid response enabled and no responses have been submitted yet, the LMS view for instructors looks like the screenshot below. We should come up with something nicer.

![ss 2018-03-16 at 11 11 52](https://user-images.githubusercontent.com/14932219/37533942-ba3ab754-2919-11e8-9e14-27b0e7131f52.png)

**Comment by roberthouse54** [comment]
This is addressed in a separate issue:
