### ISSUE TITLE
CSS and other style changes

### ISSUE THREAD

**Issue by noisecapella** [mitodl/rapid-response-xblock#42]
![](https://user-images.githubusercontent.com/20047260/37534998-c76ae07c-291c-11e8-9330-c919714e9a74.png)

We should:
 - style the switcher where we can (select styling is difficult but I feel like this is in the realm of CSS)
 - style open responses button
 - grey background
 - timer (if not already done in #33)

**Comment by pdpinch** [comment]
@roberthouse54 how much of this can you do?

**Comment by roberthouse54** [comment]
Probably all of it apart from the timer, which we do not currently have.

**Comment by pdpinch** [comment]
Cool. I'll assign it to you.

The timer is still on the bubble, depending on feedback.

**Comment by pdpinch** [comment]
@roberthouse54 @noisecapella what's the status of this issue?

**Comment by noisecapella** [comment]
It's not complete. I'm waiting until #46 is merged and #33 is done before I can see what pieces are missing specifically at that point

**Comment by noisecapella** [comment]
I think I clobbered the studio CSS when I edited it during these PRs, so we should check that too

**Comment by noisecapella** [comment]
IE11 works fine. The select widget is ugly with our margin and padding changes but I'm not sure it's worth continually tweaking for IE's benefit
