### ISSUE TITLE
Add this package to edx-platform requirements

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#52]
At some point we'll need to add this package (`rapid-response-xblock`) to a requirements file in the mitodl fork of `edx-platform`. `requirements/edx/github.txt` probably makes the most sense as the `edx-sga` dependency is included there in a section titled `# Third Party XBlocks`

**Comment by pdpinch** [comment]
I think this was done in https://github.com/mitodl/edx-platform/pull/86
