### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by noisecapella** [mitodl/rapid-response-xblock#58]
We don't have any error handling right now. If something goes wrong the timer and response polling will stop and the user will need to refresh the browser. We should put up a message saying 'Something went wrong, please try refreshing the browser' so the user has a next step they can take

**Comment by roberthouse54** [comment]
Lets cover the entire Live Response card with a transparent black div, with the error message inside:

![image](https://user-images.githubusercontent.com/20047260/41484173-cfafc908-70a9-11e8-922b-8708243357cf.png)

**Comment by pdpinch** [comment]
Moving this to In Progress, since there's a PR open
