### ISSUE TITLE
Rescoring fails on problems with rapid response 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#70]
Steps to Reproduce:

1. Create a course with one graded problem
2. Enable Rapid Response
3. In LMS, submit an answer (not sure if this requires that you are an instructor or a student)
4. In the instructor dashboard in LMS, under student admin, rescore the problem for all students

### expected behavior:

Rescore tasks succeeds (no change in this case)

### actual behavior:

Rescore task fails with error 'StructuredTagsAside' object has no attribute 'location'

![screen shot 2018-10-26 at 12 24 54 pm](https://user-images.githubusercontent.com/430126/47580030-c65b0b80-d91b-11e8-89f0-58670399d2a1.png)

Test course at https://mitx-qa.mitx.mit.edu/courses/course-v1:MITx+rpr.100+2018_Fall/instructor#view-student_admin

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you take a look at this on Monday?

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by amir-qayyum-khan** [comment]
Reproduced issue on branch mitx/hawthorn
### Steps to reproduce are:
- setup a course with rapid response block
- login and staff and enroll learner
- go to problem and click `open new response` on rapid response widget.
- take a staff and a student and attempt problem when and close repose
- go to instructor dashboard and reset all scores

<img width="1204" alt="screen shot 2018-10-29 at 7 37 52 pm" src="https://user-images.githubusercontent.com/10431250/47657041-279c0c80-dbb2-11e8-9ec7-5333e6a8cc5c.png">

**Comment by amir-qayyum-khan** [comment]
@pdpinch this is working fine on my branch 
https://github.com/edx/edx-platform/pull/19089

you need to cherry pick my commit and test there

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/mitodl/edx-platform/pull/102
