### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by noisecapella** [mitodl/rapid-response-xblock#72]
- We should add an explicit step to add the rapid response package to the relevant requirements file.
 - The single quotes in the JSON code snippet should be changed to double, and the `ALLOW_ALL_ADVANCED_COMPONENTS: true` should be changed to have quotes, so that these code snippets can be copied and pasted into the file without modification
 - Should we add instructions on where `cms.env.json` and `lms.env.json` are located or how to modify them within the docker environment? Does a user need to modify them in both the lms shell and studio shells?
 - We should add instructions on how to modify the docker devstack environment to mount the rapid response directory.

**Comment by pdpinch** [comment]
@mitodl/devops @gsidebo what are you recommendations on this?

**Comment by tasawernawaz** [comment]
+1 for opening this issue @noisecapella .

I am trying to setup rapid response xblock on my local machine with the help of @gsidebo. I would love to have an updated readme file.
