### ISSUE TITLE
Studio user documentation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#75]
Our current ReadMe only covers developer documentation. We need some information about how to install it (#72) and how to use it. 

I think @NotoriousMKD has written some end user documentation for this, but I'm not sure where it is / how to link to it.

**Comment by NotoriousMKD** [comment]
It's in our zendesk knowledge base! 

[Studio Documentation](https://odl.zendesk.com/hc/en-us/articles/360007744011-Rapid-Response-for-Studio)
[XML Documentation](https://odl.zendesk.com/hc/en-us/articles/360007744151-Rapid-Response-for-XML)
