### ISSUE TITLE
Django version conflict

### ISSUE THREAD

**Issue by noisecapella** [mitodl/rapid-response-xblock#95]
There is a `django==2.2.17` requirement in `setup.py` but my devstack instance has Django 2.2.18, and there is an error message about the conflict:

    edx.devstack.lms                  | 2021-03-29 16:09:15,922 WARNING 18 [xblock.plugin] [user 8] [ip 172.30.0.1] plugin.py:144 - Unable to load XBlockAside 'rapid_response_xblock'
    edx.devstack.lms                  | Traceback (most recent call last):
    edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/xblock/plugin.py", line 141, in load_classes
    edx.devstack.lms                  |     yield (class_.name, cls._load_class_entry_point(class_))
    edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/xblock/plugin.py", line 70, in _load_class_entry_point
    edx.devstack.lms                  |     class_ = entry_point.load()
    edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
    edx.devstack.lms                  |     self.require(*args, **kwargs)
    edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
    edx.devstack.lms                  |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
    edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    edx.devstack.lms                  |     raise VersionConflict(dist, req).with_context(dependent_req)
    edx.devstack.lms                  | pkg_resources.VersionConflict: (Django 2.2.18 (/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages), Requirement.parse('django==2.2.17'))

**Comment by pdpinch** [comment]
Dependabot already opened a PR for this: #94

**Comment by noisecapella** [comment]
@pdpinch I'm not sure we want to pin to that exact version because it will break again next Django release. @gsidebo I noticed this was changed from `django>=1.8,<3.0` in #87. Do you know if pinning to the specific version is necessary or is it enough to change it to `django>=2.2,<3.0` or similar?

**Comment by pdpinch** [comment]
@arslanashraf7 do you think we could use a range, as George suggests?

**Comment by gsidebo** [comment]
Off the top of my head I can't think of a reason we'd need that specific Django version instead of a range

**Comment by arslanashraf7** [comment]
> @arslanashraf7 do you think we could use a range, as George suggests?

@pdpinch , Yes I think we should use a range as @noisecapella suggested and I also don't think of any reason to not use a range(as Gavin said), although it will support a range of edX devstack releases as well.

**Comment by arslanashraf7** [comment]
Closing, Associated PR is merged and package is released.
